<?php

namespace App\Filament\Resources\FopperResource\Pages;

use App\Filament\Resources\FopperResource;
use Filament\Actions\CreateAction;
use Filament\Resources\Pages\ListRecords;

class ListFoppers extends ListRecords
{
    protected static string $resource = FopperResource::class;

    public int $targetId;

    public function mount(): void
    {
        parent::mount(); // TODO: Change the autogenerated stub

        session()->put('targetId', $this->targetId);
    }

    protected function getHeaderActions(): array
    {
        return [
            CreateAction::make()
        ];
    }
}
