<?php

namespace App\Models;

use App\Enums\CadeauStatus;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

class Cadeau extends Model implements HasMedia
{
    use SoftDeletes, InteractsWithMedia;

    protected $fillable = [
        "title",
        "description",
        "status",
        "price",
        "location_type",
        "location_url",
        "location_other",
        "list_user_id"
    ];


    protected function casts(): array
    {
        return [
            'status' => CadeauStatus::class
        ];
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($cadeau) {
            $cadeau->status = CadeauStatus::AVAILABLE;
            $cadeau->created_by_user_id = auth()->id();
        });
    }

    public function createdByUser(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by_user_id');
    }

    public function listUser(): BelongsTo
    {
        return $this->belongsTo(User::class, 'list_user_id');
    }

    public function reservedByUser(): BelongsTo
    {
        return $this->belongsTo(User::class, 'reserved_by_user_id');
    }

    /**
     * Returns the 'lat' and 'lng' attributes as the computed 'location_address' attribute,
     * as a standard Google Maps style Point array with 'lat' and 'lng' attributes.
     *
     * Used by the Filament Google Maps package.
     *
     * Requires the 'location_address' attribute be included in this model's $fillable array.
     *
     * @return array
     */

    public function getLocationAddressAttribute(): array
    {
        return [
            "lat" => (float)$this->lat,
            "lng" => (float)$this->lng,
        ];
    }

    public function setPriceAttribute($value){
        $this->attributes['price'] = number_format($value, 2, '.', '');
    }

    public function getPriceAttribute($value){
        return number_format($value, 2, '.', '');
    }
}
