<?php

namespace App\Filament\Resources\CadeauResource\Pages;

use App\Filament\Resources\CadeauResource;
use App\Models\Cadeau;
use Filament\Actions\CreateAction;
use Filament\Resources\Pages\ListRecords;

class ListCadeaus extends ListRecords
{
    protected static string $resource = CadeauResource::class;

    protected static ?string $breadcrumb = "";

    public int $listId;

    public function mount(): void
    {
        parent::mount(); // TODO: Change the autogenerated stub

        session()->put('listId', $this->listId);
    }

    protected function getHeaderActions(): array
    {

        return [
            CreateAction::make()
                ->visible(fn () => $this->listId === auth()->id()),
        ];
    }
}
